archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
builds:
  - hooks:
      post:
        - upx --best --lzma "{{ .Path }}"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
dockers:
  - dockerfile: Dockerfile.release
    image_templates:
      - "ghcr.io/devopsbox-io/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/devopsbox-io/{{.ProjectName}}:latest"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/devopsbox-io/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/devopsbox-io/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
